//
// Created by S.Morgenthaler on 14/05/2023.
//

#ifndef JUMPERBALLAPPLICATION_STOREVALIDATIONPAGE_H
#define JUMPERBALLAPPLICATION_STOREVALIDATIONPAGE_H


class StoreValidationPage {

};


#endif //JUMPERBALLAPPLICATION_STOREVALIDATIONPAGE_H
