//
// Created by S.Morgenthaler on 29/01/2023.
//

#ifndef JUMPERBALLAPPLICATION_RENDERGROUPSMANAGER_H
#define JUMPERBALLAPPLICATION_RENDERGROUPSMANAGER_H
#endif //JUMPERBALLAPPLICATION_RENDERGROUPSMANAGER_H
